### ISSUE TITLE
Tracking progress to 1.0.0-beta

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire-js#1]
TODO:
- [x] Feature complete
  - [x] Functions
  - [x] array methods
  - [x] other classes
  - [x] Statics (aka enums)
  - [x] [gfor](http://www.arrayfire.com/docs/page_gfor.htm)
  - [ ] make it as async: https://github.com/arrayfire/arrayfire-js/issues/9
- [x] Atleast two different working examples (other than hello world)
  - [x] pi
  - [x] neural network with mnist
- [ ] AFArray, math functions, device functions, vector algorithms, gfor fully documented, skeleton for full documentation
  - [x] AFArray
  - [ ] math functions
  - [x] device functions
  - [ ] vector algorithms
  - [ ] gfor
  - [ ] skeleton
- [ ] Basic unit tests covering AFArray methods, indexing operators, essential math functions, gfor and vector algorithms
  - [ ] AFArray
  - [x] math functions
  - [x] device functions
  - [ ] vector algorithms
  - [x] gfor
- [x] Fixes
  - [x] [Make sure those functions are async](https://github.com/arrayfire/arrayfire_js/issues/2)

**Comment by unbornchikken** [comment]
It's feature complete as of v0.12.0.

**Comment by unbornchikken** [comment]
@umar456 As you've noticed I'm very low on spare time nowadays, I'm keen on moving forward my [workflow module](https://github.com/workflow-4-node/workflow-4-node) to get v1 released, because we've started to use that in production at [SWICON](http://swicongroup.com/en/). If you could put there some effort from your side, then we can release a v1 of this module. Once we achieve that, I'll try to promote us on Node Weekly ([I was there with my other module once](http://nodeweekly.com/issues/87)), that will secure us 100+ instant GH stars for sure. ;)

**Comment by umar456** [comment]
@unbornchikken I have very recently finished a project which was taking a lot of my time. I should be able to make some progress on this in the coming week.

**Comment by unbornchikken** [comment]
obsolete. will start anew issue for tracking this
